version: '2'
services:
    simplespringapplication-app:
        image: simplespringapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://simplespringapplication-mysql:3306/simplespringapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    simplespringapplication-mysql:
        extends:
            file: mysql.yml
            service: simplespringapplication-mysql
